#!/bin/bash 

HOSTNAME=`hostname`
TIMEZONE=`timedatectl | grep "Time zone" | awk {'print $3, $4, $5'}`
USER=`whoami`
OS=`hostnamectl | grep "Operating System" | awk {'print $3, $4, $5'}`
DATE=`date | awk {'print $2, $3, $4, $5'}`
UPTIME=`uptime -p | awk {'print $2, $3, $4, $5'}`
UPTIME_SEC=`cat /proc/uptime | awk {'print $1'}`
IP=`ifconfig | grep -m 1 inet | awk {'print $2'}`
MASK=`ifconfig | grep -m 1 netmask | awk {'print $2'}`
GATEWAY=`ip route | grep -m 1 default | awk {'print $3'}`
RAM_TOTAL=`free -m | grep "Mem" | awk '{printf "%.3f GB", ($2/1024)}'`
RAM_USED=`free -m | grep "Mem" | awk '{printf "%.3f GB", ($3/1024)}'`
RAM_FREE=`free -m | grep "Mem" | awk '{printf "%.3f GB", ($4/1024)}'`
SPACE_ROOT=`df -hBM | grep -m 1 /dev/ | awk '{printf "%.2f MB", ($2)}'`
SPACE_ROOT_USED=`df -hBM | grep -m 1 /dev/ | awk '{printf "%.2f MB", ($3)}'`
SPACE_ROOT_FREE=`df -hBM | grep -m 1 /dev/ | awk '{printf "%.2f MB", ($4)}'`